name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOTNET_NOLOGO: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.x'
      - name: Check versions
        run: |
          pwsh -Command '$PSVersionTable'
          dotnet --version
          dotnet --list-sdks
      - name: Set +x for *.ps1
        shell: bash
        run: chmod +x *.ps1
      - name: pwd
        shell: pwsh
        run: Get-Location
      - name: Build and analyze
        shell: pwsh
        run: |
          dotnet build --configuration Release
          ./run-test.ps1
      - name: Pack nugets
        run: ./run-pack.ps1
      - name: Push-nugets
        env:
            NUGET_FEED: https://api.nuget.org/v3/index.json
            NUGET_KEY: ${{ secrets.NUGET_ORG_API_KEY }}
        run: ./run-push.ps1

